### ISSUE TITLE
magic numbers

### ISSUE THREAD

**Issue by damencki** [kenzywa/table-application#5]
nameTextField.topAnchor.constraint(equalTo: view.topAnchor, constant: 100).isActive = true
        nameTextField.rightAnchor.constraint(equalTo: view.rightAnchor, constant: -150).isActive = true
        nameTextField.bottomAnchor.constraint(equalTo: view.topAnchor, constant: 130).isActive = true

**Comment by kenzywa** [comment]
Are the numbers too big?

**Comment by damencki** [comment]
https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования

**Comment by kenzywa** [comment]
Solved
