### ISSUE TITLE
separate layout and bindings

### ISSUE THREAD

**Issue by damencki** [kenzywa/table-application#6]
nameTextField.text = employee?.name
        nameTextField.topAnchor.constraint(equalTo: view.topAnchor, constant: 100).isActive = true
        nameTextField.rightAnchor.constraint(equalTo: view.rightAnchor, constant: -150).isActive = true
        nameTextField.bottomAnchor.constraint(equalTo: view.topAnchor, constant: 130).isActive = true
        nameTextField.textAlignment = .center
        nameTextField.font = nameTextField.font?.withSize(20)

**Comment by kenzywa** [comment]
Solved

**Comment by damencki** [comment]
> Solved

commit?

**Comment by kenzywa** [comment]
Commited

**Comment by damencki** [comment]
nameTextField.text = employee?.name
        nameTextField.topAnchor.constraint(equalTo: view.topAnchor, constant: CGFloat(innerPadding.topSpaceBewteenTopOfViewAndName)).isActive = true

**Comment by kenzywa** [comment]
Solved
